auth
Simple2B/flask.app pull request #14
Opened 2023-04-11 15:06 UTC by JackScher

register & reset password

2023-04-11 18:04 UTC, kipod requested changes
Looks like joke

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/forgot.html
> +    <meta name="viewport" content="width=device-width,initial-scale=1" />
WRONG WAY.
In the project, we have a base template: `base.html`, all other templates need extent it...

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/forgot.html
> +        <!--  -->
what do this line?

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/forgot.html
> +              {{form.email.label(class='block mb-2 text-sm font-medium text-gray-900 dark:text-white')}} {{form.email(class='bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:r
use `<!-- prettier-ignore -->`

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/login.html
> +          role="alert"
need extend base template...

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/register.html
> +              <path
need extend the base template

2023-04-11 18:04 UTC, kipod commented on app/templates/auth/reset_password.html
> +      <body class="bg-gray-50 dark:bg-gray-900">
return code this `{% extends 'base.html' %} {% block content %}`

2023-04-11 18:04 UTC, kipod commented on tests/test_auth.py
> -        assert "bg-green-500" in response.data.decode()
👍 super fix!

2023-04-12 15:31 UTC, StoliarskyiKostiantyn requested changes

2023-04-12 15:31 UTC, StoliarskyiKostiantyn commented on app/templates/auth/forgot.html
> +  {% endfor %} {% endif %} {% endwith %}
We don't need those flash messages in this pages, we already have them in base, you need to remove them from here

2023-04-12 15:31 UTC, StoliarskyiKostiantyn commented on app/templates/auth/register.html
> +  {% endwith %}
same here

2023-04-12 15:31 UTC, StoliarskyiKostiantyn commented on app/templates/auth/register.html
> +              error in form.errors.password %}
Please pass more <!-- prettier-ignore --> to make code look more readalbe (look for example in base and login)

2023-04-12 15:31 UTC, StoliarskyiKostiantyn commented on app/templates/auth/reset_password.html
> +        </svg>
same about flash messages

2023-04-12 15:31 UTC, StoliarskyiKostiantyn commented on tests/test_auth.py
> +        assert "toast" in response.data.decode()
i think we could add test for different toasts

2023-04-13 07:24 UTC, StoliarskyiKostiantyn approved these changes

2023-04-13 07:24 UTC, merged