fix production docker
Simple2B/flask.app pull request #24
Opened 2023-04-20 09:01 UTC by JackScher

2023-04-20 12:48 UTC, kipod requested changes
This is the wrong fix...

2023-04-20 12:48 UTC, kipod commented on app/views/user.py
> +    else:
no need `else`

2023-04-20 12:48 UTC, kipod commented on app/views/user.py
> +        log(log.ERROR, "Form is not valid")
```python
log(log.ERROR, "Form is not valid: [%s]", form.errors)
```

2023-04-24 15:53 UTC, StoliarskyiKostiantyn approved these changes

2023-04-27 05:59 UTC, StoliarskyiKostiantyn approved these changes

2023-06-15 05:10 UTC, closed without merging